[versions]
appcompat = "1.5.1"
version-catalog-plugin = "0.0.1"
composeMaterial = "1.3.1"
composeAnimation = "1.3.2"
composeUiTooling = "1.3.2"
composeActivity = "1.6.1"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
compose-material = { module = "androidx.compose.material:material", version.ref = "composeMaterial" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "composeAnimation" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUiTooling" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }

[plugins]
mbbk = { id = "com.mmaquera", version.ref = "version-catalog-plugin" }